src/graph_notebook/__init__.py, src/graph_notebook/magics/graph_magic.py, src/graph_notebook/notebooks/01-Getting-Started/01-About-the-Neptune-Notebook.ipynb, src/graph_notebook/notebooks/01-Getting-Started/02-Using-Gremlin-to-Access-the-Graph.ipynb, src/graph_notebook/widgets/package.json
Removing `%query_mode` line magic in favor of individual command parameterization. 
=> remove query_mode line magic

additional-databases/neptune/README.md
Added mac specific hosts file information and added a troubleshooting section
fixes #42 
=> Updated SSH tunneling with Mac specific details

src/graph_notebook/magics/graph_magic.py, src/graph_notebook/network/gremlin/GremlinNetwork.py, test/unit/network/gremlin/test_gremlin_network.py
#62
Fixed issue where `--ignore-groups` was not being honored.
=> Fixed issue where --ignore-groups flag was not working.  Issue #62

src/graph_notebook/notebooks/03-Applications/Introduction-to-Fraud-Graphs.ipynb
=> Add fraud graph notebook and seed dataset

src/graph_notebook/notebooks/03-Sample-Applications/01-Fraud-Graphs/01-Building-a-Fraud-Graph-Application.ipynb
Parameterized seed command for fraud_graph.
=> Update 01-Building-a-Fraud-Graph-Application.ipynb Parameterize Seed Command with the Fraud Data Set

additional-databases/dbpedia/README.md, additional-databases/fuseki/README.md
Additional databases to query DBPedia and localhost Fuseki
=> Additional databases to query DBPedia and localhost Fuseki

ChangeLog.md, setup.py, src/graph_notebook/__init__.py, src/graph_notebook/loader/load.py, src/graph_notebook/widgets/package.json
Reverts unintended deletions from merging #91 .
=> Partially revert #91

ChangeLog.md, src/graph_notebook/notebooks/02-Visualization/Visualization-Grouping-Coloring-Gremlin.ipynb, test/unit/notebooks/test_validate_notebooks.py
Added a notebook showing the grouping and coloring options available to Gremlin users in the notebook.
=> Groupby Coloring Options notebook

src/graph_notebook/magics/graph_magic.py
=> sparql magic now handles update queries not having table output

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> bump version to 2.1.0

ChangeLog.md, src/graph_notebook/decorators/decorators.py, test/integration/without_iam/notebook/test_gremlin_graph_notebook.py, test/integration/without_iam/notebook/test_sparql_graph_notebook.py
Issue #, if available: #125
Description of changes: 
- Variable injection will now execute any number of nested dictionary access queries made within the injection syntax.
=> Support dictionary value access inside variable injection syntax

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json, test/integration/iam/sparql/test_sparql_status_with_iam.py, test/integration/without_iam/sparql/test_sparql_status_without_iam.py
=> version bump to 2.1.3

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump version to v2.1.4, includes bugfix for incorrectly generated lockfile in v2.1.3
=> Bump version to 2.1.4

src/graph_notebook/seed/queries/sparql/epl/0_epl_data.txt
- Update the Sparql/RDF EPL seed dataset file to match the updated dataset used in the EPL-SPARQL sample visualization notebook
=> Update SPARQL EPL seed dataset file

ChangeLog.md
- Keeping changelog file up to date with all recent commits.
=> ChangeLog updates

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump to major version 3.0.0 for the openCypher update.
=> Bump version to 3.0.0

ChangeLog.md
- Sync v3.0.0 ChangeLog notes with new updates
=> Update v3.0.0 ChangeLog

ChangeLog.md, src/graph_notebook/network/gremlin/GremlinNetwork.py, src/graph_notebook/notebooks/01-Getting-Started/04-Social-Network-Recommendations-with-Gremlin.ipynb, test/unit/network/gremlin/test_gremlin_network.py
- Fixed error caused by Gremlin visualizer incorrectly recognizing some query results as elementMaps
- Fixed a typo in a sample notebook query
=> Fix Gremlin visualizer bug

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump version to 3.0.1 for bugfixes
=> Bump version to 3.0.1

ChangeLog.md, src/graph_notebook/network/gremlin/GremlinNetwork.py, test/unit/network/gremlin/test_gremlin_network.py
- Fixed a bug that was some Gremlin queries using the `valueMap` step to be visualized incorrectly
=> Fix incorrect visualizations of Gremlin results returned by valueMap

ChangeLog.md, src/graph_notebook/network/gremlin/GremlinNetwork.py, test/unit/network/gremlin/test_gremlin_network.py
- Fixed handling of custom path values generated by `project()` steps; blank edges are now correctly generated for these queries
- Correctly display map property values in node tooltips
- Fixed node id generation
=> More Gremlin visualization bugfixes

src/graph_notebook/seed/load_query.py
Fixes Issue #168 
Handle the case where the user selects the blank line in the top %seed dropdown and the second dropdown then contained the wrong text.
=> Fix issue with seed and blank lines #168

src/graph_notebook/notebooks/04-Machine-Learning/neptune_ml_utils.py
* Adding some helper functions to neptune_ml utils to get node embeddings, model predictions and performance metrics
@bechbd 
=> adding tooling getting embeddings for all tasks, and get predictions for node class/node regression

ChangeLog.md, src/graph_notebook/neptune/client.py
Issue #, if available: #167
- Fix an issue with Neptune ML where export requests were not being signed correctly
=> Fix Neptune ML Export command bug

README.md, src/graph_notebook/notebooks/02-Visualization/Air-Routes-SPARQL.ipynb, src/graph_notebook/notebooks/02-Visualization/Blog Workbench Visualization.ipynb, src/graph_notebook/notebooks/03-Sample-Applications/01-Fraud-Graphs/01-Building-a-Fraud-Graph-Application.ipynb, src/graph_notebook/notebooks/03-Sample-Applications/02-Knowledge-Graphs/01-Building-a-Knowledge-Graph-Application-openCypher.ipynb, src/graph_notebook/notebooks/03-Sample-Applications/02-Knowledge-Graphs/01-Building-a-Knowledge-Graph-Application.ipynb, src/graph_notebook/notebooks/03-Sample-Applications/03-Identity-Graphs/01-Building-an-Identity-Graph-Application.ipynb, src/graph_notebook/notebooks/03-Sample-Applications/03-Identity-Graphs/02-Data-Modeling-for-Identity-Graphs.ipynb, src/graph_notebook/notebooks/04-Machine-Learning/Neptune-ML-00-Getting-Started-with-Neptune-ML-Gremlin.ipynb, src/graph_notebook/notebooks/04-Machine-Learning/Neptune-ML-01-Introduction-to-Node-Classification-Gremlin.ipynb, src/graph_notebook/notebooks/04-Machine-Learning/Neptune-ML-02-Introduction-to-Node-Regression-Gremlin.ipynb, src/graph_notebook/notebooks/04-Machine-Learning/Neptune-ML-03-Introduction-to-Link-Prediction-Gremlin.ipynb, src/graph_notebook/notebooks/04-Machine-Learning/Neptune-ML-04-Introduction-to-Edge-Classification-Gremlin.ipynb, src/graph_notebook/notebooks/04-Machine-Learning/Neptune-ML-05-Introduction-to-Edge-Regression-Gremlin.ipynb
- Replace references to a term(where functionally possible) for regionalization support.
=> Refactor terminology in sample notebooks and README

additional-databases/blazegraph/README.md, additional-databases/dbpedia/README.md, additional-databases/fuseki/README.md, additional-databases/gremlin-server/README.md
Issue #, if available: #197
- Revised Blazegraph setup documentation in `additional-databases` to have the correct instructions
- Removed extraneous parameters from other setup documentation files
=> Additional db updates

src/graph_notebook/magics/graph_magic.py
- Handle errors caused by using `%load` with a non-Neptune host
- Add variable injection back for `%load` source parameter 
=> Additional %load error handling

src/graph_notebook/magics/graph_magic.py, src/graph_notebook/magics/metadata.py, test/unit/graph_magic/test_opencypher_metadata.py
- Fixed a bug where query metadata was not being generated correctly for `%%oc bolt` query results.
=> Fix OC Bolt metadata

additional-databases/graphdb/README.md
Description of changes: GraphDB configuration example in additional-databases to use to connect to Graph-Notebook library
=> GraphDB configuration example proposal

.github/workflows/unit.yml, test/unit/notebooks/test_validate_notebooks.py
- Modify package build and installation steps in unit test workflow, to account for changes in #271.
=> Fix unit test workflow

ChangeLog.md, src/graph_notebook/magics/graph_magic.py, src/graph_notebook/network/opencypher/OCNetwork.py, test/unit/network/opencypher/test_opencypher_network.py
- Fixed a bug where empty nodes returned from openCypher `DELETE` queries were not being handled properly
- Fixed rendering of openCypher widgets for queries returning empty result sets
=> Bugfixes for openCypher result widgets

src/graph_notebook/notebooks/05-Data-Science/01-Identifying-1st-Person-Synthetic-Identity-Fraud-Using-Graph-Similarity.ipynb
Nice examples of similarity! Some additional comments:
Deleted an extra blank cell at the top.
Very similar changes as the other notebook.
Line 335, please review rephrasing.
Line 475, please review rephrasing.
Line 526 - at the end of this line, I was not sure what to make of it, until I kept reading. Can we make this more explicit, e.g., "these nodes share a significant number of common features so we need to mark them as similar for further investigation."
=> First-person fraud notebook updates

src/graph_notebook/notebooks/05-Data-Science/02-Logistics-Analysis-using-a-Transportation-Network.ipynb
Line 375 - Can we define what is an NP-hard problem for someone who isn't familiar with the term?
Line 413 - Is it possible to comment on the results of the last problem "minimum distance required to travel to all 150 airports..." so that readers know what to draw from the query?
=> Logistics Notebook edits

src/graph_notebook/configuration/generate_config.py, src/graph_notebook/configuration/get_config.py, test/integration/IntegrationTest.py, test/integration/iam/ml/__init__.py, test/unit/configuration/test_configuration_from_main.py
- Modifying a few unit and integration tests to account for the new `proxy_port` and `proxy_host` config parameters.
=> Test fixes

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> Bump to 3.5.0

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> Bump to 3.5.1

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> Bump to 3.5.2

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> Bump to 3.5.3

ChangeLog.md, test/unit/notebooks/test_validate_notebooks.py
- Updates notebook unit test and added changelog entry for #338.
=> Changelog and unit test updates for ML-06 notebook changes

ChangeLog.md, additional-databases/sagemaker/README.md, additional-databases/sagemaker/install-graph-notebook-lc-cn.sh
- Added new sample lifecycle configuration script for China regions.
=> Add SageMaker installation script for China regions

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> Bump to 3.6.0

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> Bump to 3.6.1

ChangeLog.md, src/graph_notebook/notebooks/01-Getting-Started/01-About-the-Neptune-Notebook.ipynb
- Updated `01-About-the-Neptune-Notebook` with openCypher magic query examples and sample application notebooks.
=> Update introduction sample notebook for openCypher

ChangeLog.md, src/graph_notebook/magics/graph_magic.py
Issue #, if available: #119
- Fixed JupyterLab not displaying status widgets after submitting `%load` job
- Fixed `%load` not using region specified via UI widget or arguments
- Added status message and wheel for initial load request submission
=> %load status output fixes and improvements

ChangeLog.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump package version to 3.7.0.
=> Bump to 3.7.0

README.md
- Update README with additional links to documentation on query magics and common arguments.
=> Link additional query magic argument docs in the README

ChangeLog.md, src/graph_notebook/decorators/decorators.py, src/graph_notebook/network/EventfulNetwork.py, test/integration/without_iam/notebook/test_gremlin_graph_notebook.py, test/integration/without_iam/notebook/test_sparql_graph_notebook.py
Issue #, if available: #408
- Cell variable injection now support access to elements in list and tuple type local variables. The injected variable can now include any mixture of nested data structures.
Example usage:
=> Added support for list/tuple element access in cell variable injection

src/graph_notebook/neptune/client.py
- Removed extraneous code preventing the base query status method from functioning properly.
=> Fix requests error in query status magics

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump package version to 3.7.1
=> Release 3.7.1

src/graph_notebook/notebooks/01-Getting-Started/02-Using-Gremlin-to-Access-the-Graph.ipynb
Description of changes: Fix property key in gremlin statement as per TinkerPop’s "Modern" graph
As per https://tinkerpop.apache.org/docs/current/images/tinkerpop-modern.png, the property key is `lang` and value is `java` for node with id `5`.
=> Fix property key in gremlin statement

.github/workflows/unit.yml, ChangeLog.md
- Unblocking the unit test workflow runs for pull requests created from external branches.
=> Run unit tests on external pull requests

src/graph_notebook/notebooks/04-Machine-Learning/Sample-Applications/03-Real-Time-Fraud-Detection-Using-Inductive-Inference.ipynb
Description of changes: Minor edits to the Fraud OII noteboks to reflect documented behavior for tranductive inference and nondeterministic sampling
=> minor edit to examples for consistent behavior with documentation

src/graph_notebook/notebooks/04-Machine-Learning/Sample-Applications/03-Real-Time-Fraud-Detection-Using-Inductive-Inference.ipynb
- Corrected a typo in the the `03-Real-Time-Fraud-Detection-Using-Inductive-Inference` notebook.
=> Correct a typo in 03-Real-Time-Fraud-Detection-Using-Inductive-Inference ML notebook

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump package version to 3.7.2
=> Release 3.7.2

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump package version to 3.7.3
=> Bump to 3.7.3

ChangeLog.md, src/graph_notebook/notebooks/04-Machine-Learning/Neptune-ML-04-Introduction-to-Edge-Classification-Gremlin.ipynb
Description of changes: Update broken doc links in Neptune-ML-04-Introduction-to-Edge-Classification-Gremlin.ipynb
=> Update broken doc links in Neptune-ML-04-Introduction-to-Edge-Classification-Gremlin.ipynb

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump package version to 3.8.0
=> Bump to 3.8.0

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump package version to 3.8.1
=> Bump to 3.8.1

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bump package version to 3.8.2
=> Bump to 3.8.2

test/integration/iam/opencypher/test_opencypher_query_with_iam.py
- Fixes issue seen at: https://github.com/aws/graph-notebook/actions/runs/5721238577/job/15502528832
=> Fix unit test workflow failing on type check assertion statement

src/graph_notebook/neptune/client.py
=> Recognize TS domains as Neptune endpoints

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bumping package version to 3.9.0.
=> Release 3.9.0

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Incrementing package to patch version 4.0.1.
=> Release 4.0.1

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Incrementing package version to 4.0.2.
=> Release 4.0.2

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Incrementing package version to 4.1.0.
=> Release 4.1.0

ChangeLog.md, src/graph_notebook/notebooks/01-Neptune-Database/02-Visualization/Grouping-and-Appearance-Customization-Gremlin.ipynb
- Added documentation to fix certain %graph_notebook_vis_options in samples failing to render icons correctly on JupyterLab 3 and Classic Notebook 7.
=> Document FontAwesome 5 settings

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Bumping package version to 4.3.0.
=> Release 4.3.0

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> Release 4.3.1

ChangeLog.md, README.md, requirements.txt, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Incrementing package version to 4.4.0.
- Fix accidental reversion of #600 
=> Release 4.4.0

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Incrementing package version to 4.4.1.
=> Release 4.4.1

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Increment package version to 4.5.0
=> Release 4.5.0

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
=> Release 4.5.1

additional-databases/sagemaker/sagemaker-notebook-lifecycle/install-graph-notebook-lc-cn.sh, additional-databases/sagemaker/sagemaker-notebook-lifecycle/install-graph-notebook-lc.sh
=> Revert SageMaker kernel name

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Increment package version to 4.5.2
=> Release 4.5.2

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Increment package version to 4.6.0
=> Release 4.6.0

ChangeLog.md, README.md, src/graph_notebook/__init__.py, src/graph_notebook/widgets/package.json
- Increment package version to 4.6.1
=> Release 4.6.1

src/graph_notebook/magics/graph_magic.py
- EdgeOnlyLoad parameter is only supported on either CSV format bulk loads.
=> Pass edgeOnlyLoad parameter only for CSV
