- README.md
- setup.py
- src/graph_notebook/__init__.py
- src/graph_notebook/widgets/package.json
Issue #, if available: None
- Change package version requirements so AWS Sagemaker can install graph-notebook without any issues.
- Small updates to README
> Sagemaker Compatibility

- additional-databases/gremlin-server/README.md
Minor changes to instructions
1. Channelizer string correction
2. graph_notebook_config connection string fixed
3. dataset name as it appears in graph notebook from "air-routes" to "airports"
> Update Gremlin server connection README.md

- src/graph_notebook/__init__.py
- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/configuration/get_config.py
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/request_param_generator/default_request_generator.py
- src/graph_notebook/request_param_generator/sparql_request_generator.py
- src/graph_notebook/sparql/query.py
- src/graph_notebook/status/get_status.py
- src/graph_notebook/widgets/package.json
- test/unit/configuration/test_configuration.py
- test/unit/configuration/test_configuration_from_main.py
Issue #, if available: #39
- Support to allow namespace specification for Blazegraph endpoints by specify the prefix to the sparql endpoint being queried.
- Add new config section for sparql-specific items
> Support for specifying prefix-paths

- src/graph_notebook/magics/graph_magic.py
- test/integration/notebook/test_sparql_graph_notebook.py
- specify explain prefix_path param explicitly in `%%sparql explain` magic variant
> pass sparql prefix_path param explicitly to explain

- README.md
- src/graph_notebook/__init__.py
- src/graph_notebook/widgets/package.json
- Update README to include all magic commands installed by this package.
- Remove references to `query_mode` which was removed when `graph-notebook` moved to version 2.0
> update README to include all magic commands added by graph-notebok

- README.md
- src/graph_notebook/__init__.py
- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/request_param_generator/sparql_request_generator.py
- src/graph_notebook/sparql/query.py
- src/graph_notebook/widgets/package.json
- test/integration/notebook/test_sparql_graph_notebook.py
- test/integration/sparql/sparql_query_without_iam.py
- test/unit/notebooks/test_validate_notebooks.py
- test/unit/request_param_generator/test_sparql_request_generator.py
Issue #, if available: 61
Change sparql custom path logic to no longer append `/sparql` to the end. This should help give support to all SPARQL endpoints.
> Rework sparql custom path

- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #46
- Print the total execution time of the bulk loader query when running the %load magic command.
> Print execution time when running %load command

- src/graph_notebook/loader/load.py
- src/graph_notebook/magics/graph_magic.py
Issue #, if available:  Issues 14 and 24
Description of changes:  Adding parameter flags to `%load_status` magic in order to include details and errors for bulk loader status queries.  Also including the necessary parameters for pagination (page and errorsPerPage) per the Neptune documentation here:  https://docs.aws.amazon.com/neptune/latest/userguide/load-api-reference-status-requests.html
> Adding support for %load_status details, errors, and pagination.

- ChangeLog.md
- setup.py
- src/graph_notebook/__init__.py
- src/graph_notebook/widgets/package.json
Issue #, if available: #81
- Pin version of ipython to ensure we have access to jupyter namespace in magic commands
> pin ipython version

- ChangeLog.md
- src/graph_notebook/__init__.py
- src/graph_notebook/loader/load.py
- src/graph_notebook/widgets/package.json
- Add default values when checking for load_status. Defaults taken from [public docs](https://docs.aws.amazon.com/neptune/latest/userguide/load-api-reference-status-requests.html#load-api-reference-status-request-syntax)
> add default values when checking load status

- src/graph_notebook/network/gremlin/GremlinNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
Fixed problem where queries that returned only vertex objects were nt getting the grouping fields correctly applied.  Now they will group by the label by default or by id if specified
> Issue-93 - Fixed problem with GroupBy on Vertex objects

- src/graph_notebook/magics/graph_magic.py
- Reorder when we display certain tabs in sparql and gremlin magics to get datatables showing after the metadata tab was added
> reorder tab displays to get datatables working

- ChangeLog.md
- src/graph_notebook/__init__.py
- src/graph_notebook/magics/ml.py
- src/graph_notebook/neptune/client.py
- src/graph_notebook/widgets/package.json
- Generate a new Neptune client based on the auth setting of the exporter when calling `%neptune_ml export ...` commands
> [BUG] Fix issue causing export magic commands to use neptune auth setting

- setup.py
> Fix missing Boto3 dependency in setup.py

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- src/graph_notebook/notebooks/02-Visualization/Visualization-Grouping-Coloring-Gremlin.ipynb
- test/unit/network/gremlin/test_gremlin_network.py
Issue #, if available: #97
- Enhance the Gremlin cell magic group-by parameter by allowing users to specify individual grouping behaviors for vertices that have different labels but are returned in the same set of query results.
**Usage**:
The variable containing the desired grouping behavior must be formatted as:
`
groups_var = '{"label_1":{"groupby":"property_1"},"label_2":{"groupby":"property_2"}}'
`
A valueMap step returning the label property and the grouping property(i.e. valueMap(true) or valueMap('~label','property_1'...)) must also be included in the query.
**Example:**
> Add support for grouping by different properties by label in Gremlin

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #120
- Use HH:MM:SS format for any execution times 1 minute or over
> Display %load command execution time as HH:MM:SS for large values

- ChangeLog.md
- setup.py
- src/graph_notebook/__init__.py
- src/graph_notebook/decorators/decorators.py
- src/graph_notebook/magics/ml.py
- src/graph_notebook/widgets/package.json
- Pin version of gremlinpython to <3.5.*
> Bump to version 2.1.2

- src/graph_notebook/notebooks/02-Visualization/Visualization-Grouping-Coloring-Gremlin.ipynb
Issue #, if available: #35
- Add example usage of the `-label-max-length`Gremlin magic parameter to the `Visualization-Grouping-Coloring-Gremlin` sample notebook
> Update sample notebooks with '--label-max-length' parameter usage

- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
Issue #, if available: #34, #92
- Added new `--edge-display-property` / `-de` parameter to the Gremlin cell magic. This allows for specifying what edge property value is displayed over each edge in the graph visualization. Usage is identical to the existing `--group-by` and `--display-property` parameters.
Example usage:
>  Add new --edge-display-property parameter to Gremlin magic for specifying edge labels

- src/graph_notebook/notebooks/02-Visualization/Visualization-Grouping-Coloring-Gremlin.ipynb
Issue #, if available: #34, #92
- Add example usage of the `-edge-display-property` / `-de` Gremlin magic parameter to the Visualization-Grouping-Coloring-Gremlin sample notebook
> Add usage of --edge-display-property to sample notebooks

- README.md
- Remove `iam_credentials_provider_type` option from current documentation on `%%graph_notebook_config`; IAM credentials retrieval is now handled by the Boto3 library with the client refactor in #104.
> Remove deprecated IAM config option from README

- src/graph_notebook/magics/graph_magic.py
Issue #, if available: [StackOverflow question](https://stackoverflow.com/questions/68198550/using-graph-notebook-to-connect-to-blazegraph-database)
- Fix a bug with %status throwing an error when parsing the Blazegraph status response.
> Fix %status output for Blazegraph

- src/graph_notebook/network/gremlin/GremlinNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
Issue #, if available: None
- In Gremlin graph visualizations, node tool-tips will now always match the node label when the label is modified using the `-d` parameter.
> Fix bug with Gremlin node tooltips being displayed incorrectly

- src/graph_notebook/magics/metadata.py
- test/unit/graph_magic/gremlin_profile_large_results_predicates.txt
- test/unit/graph_magic/metadata_gremlin_profile.py
- Fixed bug caused by parsing of Gremlin explain and profile text when generating the metadata results tab
> Fix bug in using Gremlin Explain/Profile with large result sets

- src/graph_notebook/network/gremlin/GremlinNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
Issue #, if available: #32
- Add support for fully visualizing Gremlin queries containing the `elementMap()`step. Edge and vertex property sets returned by `elementMap()` will now be correctly rendered in the graph. 
> Add visualization support for elementMap() Gremlin step 

- ChangeLog.md
- setup.py
- Pin RDFLib to v5.0.0 due to compatibility issues with v6.0.0, which is picked up in Python versions >=3.7.0. This is a sub-dependency of SparqlWrapper, which only requires RDFLib >= 4.0.
> Pin RDFLib version

- README.md
- Instruct users to pin the RDFLib version manually during the notebook install process.
> Pin RDFLib version in README

- src/graph_notebook/network/EventfulNetwork.py
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- src/graph_notebook/network/opencypher/OCNetwork.py
- test/unit/network/opencypher/test_opencypher_network.py
Issue #, if available: None
- Fix an issue with some openCypher visualization node tooltips being displayed incorrectly
> Fix OC node tooltips display

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
Issue #, if available: #146
- Add support for use of Neptune's Gremlin Profile API parameters in Gremlin cell magics. 
The new parameters are as follows:
`--no-results`: Removes query results from the profile output. No input value.
`--chop`: Truncates profile output at the specified character length. Accepts an integer value.
`--serializer`: Specifies how to serialize the results. Accepts any string value of valid MIME type or TinkerPop driver "Serializers" enum values. 
`--indexOps`: Adds a more detailed report of index operations to the profile output. No input value.
Please see the official Neptune documentation for more information on these options: 
https://docs.aws.amazon.com/neptune/latest/userguide/gremlin-profile-api.html#gremlin-profile-api-parameters
By …
> Support Gremlin Profile API parameters

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #50 
Added a 2 second sleep before the progress bar is removed so that the user sees it complete
> Add short sleep so progress bar can finish #50

- ChangeLog.md
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- Fixed an issue with redundant nodes and edges being included in visualizations of some Gremlin queries using the `elementMap` step
> Fixed elementMap identification

- ChangeLog.md
- src/graph_notebook/neptune/client.py
Issue #, if available: #167
- Changed request preparation to disable signing of requests being made to the endpoints of AWS services with IAM disabled.
> Disable SigV4 signing of non-IAM AWS requests

- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
Issue #, if available: #143
- Added a `--nopoll` parameter to the `%load` magic command. If this option is not specified, the notebook will continuously poll and display the bulk load status until the load is completed.
> Add %load --nopoll option

- ChangeLog.md
- README.md
- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/configuration/get_config.py
- src/graph_notebook/magics/graph_magic.py
- test/unit/configuration/test_configuration.py
- test/unit/configuration/test_configuration_from_main.py
Issue #, if available: #19
- When setting `%%graph_notebook_config`, make the parameters `auth_mode`, `load_from_s3_arn`,  and `aws_region` optional if `host` is not a Neptune endpoint.
> Make Neptune specific parameters optional when setting %%graph_notebook_config 

- ChangeLog.md
- src/graph_notebook/decorators/decorators.py
- src/graph_notebook/network/EventfulNetwork.py
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- src/graph_notebook/network/opencypher/OCNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
- test/unit/network/opencypher/test_opencypher_network.py
- Added support for specifying what sub-values to use from a multi-property as node/vertex labels in Gremlin and openCypher visualizations. Users can specify the multi-property name along with the index of the desired value.
Examples of usage:
```
my_node_labels = '{"airport":"city[0]"}'
%%gremlin -d $my_node_labels
...
```
```
%%gremlin -d city[0]
...
```
> Support use of multi-property values in vertex and edge labels

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/options/options.py
- src/graph_notebook/widgets/src/force_widget.ts
- test/unit/options/test_options.py
Issue #, if available: #74
- Added `simulationDuration` option: allows setting maximum duration of the simulation, this was previously hardcoded to 1500ms;  can also be set using the `-sd`/`--simulation-duration` option with query magics
- Added `disablePhysicsAfterInitialSimulation` option: disables physics after the first simulation has stabilized; can also be set by specifying`-sp`/`--stop-physics`
- Added new lock/unlock button to graph tab to toggle physics state
> Add new visualization physics options, and toggle button to enable/disable physics

- src/graph_notebook/network/gremlin/GremlinNetwork.py
- src/graph_notebook/network/opencypher/OCNetwork.py
- Handle cases where some JSON format strings specified directly to the `-d` or `-de` query options were not being serialized correctly to dictionary format.
> Improve handling of JSON format string inputs for -d/-de query options

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/network/opencypher/OCNetwork.py
- src/graph_notebook/seed/load_query.py
- test/integration/without_iam/opencypher/test_opencypher_query_without_iam.py
- test/integration/without_iam/opencypher/test_opencypher_status_without_iam.py
- test/unit/network/opencypher/test_opencypher_network.py
- Implement additional checks to catch TypeError being thrown when attempting to create a visualization network from an invalid openCypher list-type results set.
- Fix some issues in openCypher integration tests
> Fix TypeError thrown for certain OC list type results

- src/graph_notebook/magics/streams.py
Issue #199
When switching between the Gremlin and SPARQl streams, if there is no data on that stream, erase any displayed data from the other stream and display a message that the stream has no data.
> Fix for #199

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Added `--silent` option to `%%gremlin`, `%%sparql`, and `%%opencypher`/`%%oc` to allow for suppressing the display of all query output widgets.
> Add silent output query option

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Added `--silent` option to `%graph_notebook_vis_options` line magic, suppresses output when specified.
> Add silent option to %graph_notebook_vis_options

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #204
- Added `--named-graph-uri`, `--base-uri`, and `--allow-empty-strings` options to the `%load` magic. These enable usage of the `parserConfiguration` Neptune bulk loader parameter and its child elements.
> Add parserConfiguration options to %load

- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/configuration/get_config.py
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- src/graph_notebook/notebooks/04-Machine-Learning/neptune_ml_utils.py
- test/unit/configuration/test_configuration.py
- test/unit/configuration/test_configuration_from_main.py
Issue #, if available: #222
- Fixed an issue where mandatory AWS configuration settings were being set correctly when setting `host` to a CN region Neptune cluster endpoint
> Fixed recognition of CN region Neptune hosts

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/network/EventfulNetwork.py
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- src/graph_notebook/network/opencypher/OCNetwork.py
- src/graph_notebook/network/sparql/SPARQLNetwork.py
- src/graph_notebook/widgets/src/force_widget.ts
- test/unit/network/gremlin/test_gremlin_network.py
- test/unit/network/opencypher/test_opencypher_network.py
- test/unit/network/sparql/test_sparql_network.py
- test/unit/network/test_eventful_network.py
- Added edge tooltips matching the corresponding edge label, displayed when hovering over any graph edge.
- Added new `-le`/`--edge-label-max-length` (`-rel`/`--rel-label-max-length` for `%%oc`) parameter to query magics for extending and truncating edge labels
- Added the vertex-specific `--label-max-length` parameter to `%%sparql`
> Add edge tooltips, new query magic option for specifying edge label length

- ChangeLog.md
- README.md
- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/configuration/get_config.py
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- test/integration/IntegrationTest.py
- test/integration/iam/ml/__init__.py
Issue #, if available: #206
- Add new section to `%%graph_notebook_config` input for Gremlin-specific options
- Support for specifying the traversal source to use for Gremlin queries, in case the name of the traversal source differs from the previously hardcoded default of `g`.
> Make Gremlin traversal source configurable

- src/graph_notebook/neptune/client.py
- Added an extra condition to the GremlinServerError check to ensure that the additional help message for traversal source errors is only displayed when relevant.
> Fix conditions for traversal source error output

- src/graph_notebook/notebooks/04-Machine-Learning/neptune-ml-pretrained-model-config.json
- src/graph_notebook/notebooks/04-Machine-Learning/neptune_ml_utils.py
- Updated NeptuneML resources to use accessible models and container images when creating pre-trained model endpoints within AWS CN regions
> Update NeptuneML pre-trained model resources for CN regions

- ChangeLog.md
- requirements.txt
- setup.py
Issue #, if available: #229
- Pinned Jedi version in setup to patch a dependency bug in `ipython<=7.19`. This resolves exceptions thrown when attempting to use the tab auto-completion hints in a query cell. 
> Pin Jedi version to <0.18.0

- additional-databases/sagemaker/install-graph-notebook-lc.sh
- Updated Github version of Sagemaker install script with support for specifying graph-notebook version
- Add condition to launch Jupyter notebook with start_notebook.py only if the graph-notebook version is compatible
> Update Sagemaker installation script for older notebook versions

- src/graph_notebook/start_notebook.py
- Covered cases where the `~/.jupyter/nbconfig` directory does not exist when attempting to launch with `start_notebook.py`. If missing, this directory tree will now be generated prior modifying/creating the `notebook.json` configuration file.
> Fix possible FileNotFoundError in Jupyter startup script

- src/graph_notebook/widgets/src/force_widget.ts
Issue #, if available: #228
- Added three new buttons to the graph tab:
- Zoom Reset: restores zoom to default and centers the graph
- Full Reset: reruns the physics simulation, then fits graph to window
- Search UUID Toggle: enables/disables inclusion of property IDs in the graph search
> Add visualization UI buttons for graph reset, search refinement 

- src/graph_notebook/widgets/package.json
Issue #, if available: CVE-2021-3918
- Move to `json-schema==0.4.0` to resolve a Dependabot alert
> Upgrade json-schema version to fix vulnerability

- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #214
- Added `--no-scroll` option to query magics. If specified, each page of query results will be displayed unabridged without need for scrolling.
> Add --no-scroll option

- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/network/opencypher/OCNetwork.py
- test/unit/network/opencypher/test_opencypher_network.py
Issue #, if available: #147
- Modified `--group-by` on label for openCypher to bring it line with SPARQL and Gremlin (I.e. switched syntax from `{"airport":{"groupby":"code"}}` to `{"airport":"code"}`)
- Added grouping by node depth for openCypher queries. To color nodes bases on depth, the query must return a set of paths in list format, and users must specify `TRAVERSAL_DEPTH` as the grouping property. 
> Fix OC group-by-label, add OC group-by-depth

- src/graph_notebook/network/gremlin/GremlinNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
Issue #, if available: #244
- Fixes an issue in Gremlin graphs using path patterns, where the root node was being rendered blank if the `T.id` property was not of string type.
> Fix Gremlin vis bug with non-string vertex IDs

- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #69
- `%seed` now ignores any blank lines in seed files.
- Added `--ignore-errors` option to `%seed`. If specified, errors thrown by individual query lines will not terminate the load.
> Improve %seed error handling

- src/graph_notebook/magics/graph_magic.py
- Renamed `%%gremlin profile` arguments to be less ambiguous. Appended `--profile-` prefix to each.
> Rename gremlin profile arguments for clarity

- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/visualization/templates/gremlin_table.html
- src/graph_notebook/visualization/templates/opencypher_table.html
- src/graph_notebook/visualization/templates/sparql_table.html
Issue #, if available: #135
- Added `-r`/`--results-per-page` to query magics. This allows for specifying a custom number of entries to display per page on the query results tab.
> Add --results-per-page query option

- requirements.txt
- setup.py
Issue #, if available: GHSA-pq7m-3gw7-gq5x
- Reduce upper bound of to `ipython` dependency to `<7.17.0` to resolve a vulnerability. Not upgrading to version `>=7.31.1` at this time to maintain support for Python 3.6.
> Pin ipython<7.17.0

- src/graph_notebook/magics/graph_magic.py
- Stopped printing of root logger errors when debug logs have not been enabled by the user.
> Prevent double printing of root logger errors

- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/network/EventfulNetwork.py
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- src/graph_notebook/network/opencypher/OCNetwork.py
- src/graph_notebook/network/sparql/SPARQLNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
- test/unit/network/opencypher/test_opencypher_network.py
- test/unit/network/sparql/test_sparql_network.py
Issue #, if available: #64
- Added `-gr`/`--group-by-raw` option to `%%sparql`/`%%gremlin`/`%%oc`. If specified, nodes will be grouped based based on the raw result returned. This option will override any input to `--group-by-property`.
> Add groupby raw node result option

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/magics/streams.py
- src/graph_notebook/neptune/client.py
Normalize the options offered the user by the stream_viewer magic to be just `PropertyGraph` or `RDF`. These will then be mapped to either  the `gremlin` or `sparql`  Neptune Streams REST API endpoints. I did not map `PropertyGraph` to `pg` which would also work, to keep the notebooks compatible with older Neptune engine versions.
> Normalize stream endpoint names

- src/graph_notebook/widgets/package.json
Issue #, if available: CVE-2022-0437
- Bumped `karma` npm package version to `6.3.14` for a vulnerability fix. Confirmed that all widgets unit tests are still passing when executed using the upgraded Karma test runner.
> Bump Karma dependency to 6.3.14

- requirements.txt
- setup.py
Issue #, if available: #267
- Pinned `markupsafe` dependency to `<2.1.0`. This prevents our pinned version of the `Jinja2` parent dependency from installing the latest version, `markupsafe==2.1.0`, which it is incompatible with, breaking our user installation process.
> Pin markupsafe<2.1.0

- src/graph_notebook/widgets/package.json
Issue #, if available: CVE-2021-23495
- Bumped `karma` npm package version to `6.3.14` for a vulnerability fix. Manually verified that all `graph_notebook_widgets` unit tests are passing after the upgrade.
> Bump Karma dependency to 6.3.16

- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #274
- Modify explain/profile plan generation to replace any characters in the raw query results that can't be encoded to ASCII.
> Fix ASCII encoding error in Profile/Explain generation

- requirements.txt
- setup.py
- Bumped pinned version of `jinja2` to `3.0.3`. 
This resolves a dependency conflict between `graph-notebook` and `jupyterlab-server`, which now requires `jinja2>=3.0.3`: https://github.com/jupyterlab/jupyterlab_server/blob/main/setup.cfg#L32
We cannot allow newer versions of `jinja2` at this time. `jinja2>=3.1.0` [deprecates its older `contextfilter` class](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0); this is incompatible with with our pin of `nbconvert<6`, as a fix for the `contextfilter` deprecation is not implemented until `nbconvert==6.1.2`: https://github.com/jupyter/nbconvert/pull/1624
> Bump jinja2 from 2.10.1 to 3.0.3

- README.md
Issue #, if available: #55
- Revised installation section of README to separate instructions for Juypter Classic Notebook and JupyterLab.
> Add JupyterLab installation instructions to README

- src/graph_notebook/magics/graph_magic.py
This PR adds support for variables to the graph_notebook_config magic. This is very useful in scenarios where, for instance, the tooling launching graph_notebook pre-populates the environment with information about the DB endpoint:
```python
import os
neptune_host = os.getenv("NEPTUNE_HOST")
neptune_port = os.getenv("NEPTUNE_PORT")
```
```
%%graph_notebook_config
{
"host": "${neptune_host}",
"port": ${neptune_port},
"auth_mode": "IAM",
"iam_credentials_provider_type": "ENV",
"load_from_s3_arn": "",
"ssl": true,
"aws_region": "eu-west-1"
}
```
That makes easier the creation of "generic" notebooks that do not hardcode any configuration parameter.
> Add support for variables to graph_notebook_config magic

- ChangeLog.md
- THIRD_PARTY_LICENSES.txt
- setup.py
- Remove unused `requests-aws4auth` dependency requirement from `setup.py`, and licensing information.
> Unpin requests-aws4auth version

- README.md
- src/graph_notebook/start_jupyterlab.py
Issue #, if available: #55
- Added `start_jupyterlab.py` script for setting launch options with JupyterLab. Ensures that iPython is configured to auto-load the installed `graph_notebook.magics` extension for every new kernel.
> Add start_jupyterlab script

- ChangeLog.md
- src/graph_notebook/visualization/templates/gremlin_table.html
- src/graph_notebook/visualization/templates/opencypher_table.html
- src/graph_notebook/visualization/templates/sparql_table.html
- Added manual check for string-integer comparisons in displayed pagination options array, this fixes inconsistencies caused by browser specific implementations of the JavaScript `sort` method.
> Bugfix for displayed pagination options

- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- test/integration/without_iam/gremlin/test_gremlin_query.py
Issue #, if available: #304
- Added `-mcl`/`--max-content-length` option to `%%gremlin`. This option can be used to modify the the maximum byte size of query results accepted by the Gremlin Python client, which defaults to 10MB.
> Make max_content_length configurable via %%gremlin

- src/graph_notebook/ipython_profile/__init__.py
- src/graph_notebook/ipython_profile/configure_ipython_profile.py
- src/graph_notebook/start_jupyterlab.py
- src/graph_notebook/start_notebook.py
- Refactored `start_jupyterlab.py` script. Moved the code for setting IPython extensions to new module `graph_notebook.ipython_profile.configure_ipython_profile`, so that we can call it independently of the startup script.
> Move JupyterLab IPython config to own module

- requirements.txt
- setup.py
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #55
- Moved to using [itables](https://github.com/mwouts/itables) for applying DataTables formatting. The results table output tab will now render correctly when queries are executed in JupyterLab.
> Fix Datatables formatting for JupyterLab

- src/graph_notebook/configuration/get_config.py
- Prevents errors from occurring when `proxy_host` or `proxy_port` are not specified in `~/graph_notebook_config.json` or when running `%%graph_notebook_config`.
> Make proxy config fields optional

- src/graph_notebook/magics/graph_magic.py
- Prevent `%%sparql` widgets from failing to render when a query does not return any results.
> Fix IndexError thrown when Sparql query returns no results

- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/configuration/get_config.py
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- test/unit/configuration/test_configuration.py
- test/unit/configuration/test_configuration_from_main.py
- Added `neptune_config_allowlist` line/cell magic. Allows users to modify the allow-list for identifying Neptune endpoints during creation of `graph_notebook_config`.
For example, the following command:
```
%%neptune_config_allowlist add
localhost
```
Outputs:
```
Set Neptune config allow list to: ['amazonaws.com', 'localhost']
```
> Add neptune_config_allowlist magic

- src/graph_notebook/widgets/package.json
Issue #, if available: CVE-2022-31160
- Bumped `jquery-ui` npm package version to `1.13.2` for a vulnerability fix. Manually verified visualization widget functionality and passing `graph_notebook_widgets` unit tests following the upgrade.
> Upgrade jquery-ui to 1.13.2

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Reverting select changes made to Gremlin console tab in #297. Columns will no longer be created for individual properties in results.
- Set `opt.maxBytes=0` itables option, to prevent results being cut off when over 64KB.
> Revert Gremlin console tab to single results column

- ChangeLog.md
- Dockerfile
- docker/service.sh
Issue brought up by customer where the `GRAPH_NOTEBOOK_SSL` environment variable didn't effect the graph_notebook_config. Then some users receive permission errors when running `service.sh`. 
- Change the way bash script performs conditional checks, so now conditionals are functional
- Added `chmod +x` command to take care of permissions error during execution.
- Changelog update
> Docker: Fix Bash Script Comparisons and Permissions

- src/graph_notebook/magics/graph_magic.py
Issue #, if available:  Issue 336
Changed `%sparql_status` magic without query ID to call `sparql_status()` function instead of `sparql_cancel()` function.
> [Issue 336] Fixed %sparql_status magic to return query status without query ID.

- src/graph_notebook/magics/graph_magic.py
- test/integration/without_iam/notebook/test_gremlin_graph_notebook.py
Issue #, if available: #333
- Fixed an issue with default `%%gremlin` queries where `--store-to` was not receiving results in the returned format.
> Fix incorrect Gremlin query --store-to output

- test/integration/iam/sparql/test_sparql_status_with_iam.py
- test/integration/without_iam/notebook/test_sparql_graph_notebook.py
Issue #, if available: #336
- Add integration tests to accompany #337.
> Add tests for sparql_status without queryid

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #340
- Replace certain characters in data with their HTML entity equivalent prior to rendering the Console tab.
> Escape HTML characters when generating results table

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Fixed a visual bug occurring with `pandas<=1.3.5` (on Python<=3.7.x), where the the default Dataframe index column was unexpectedly displayed in the Gremlin query results table.
> Remove extra index column on Gremlin results table

- src/graph_notebook/magics/graph_magic.py
- Added the `--silent` option to `%load_status`, as this was missing in #326.
> Add silent option to %load_status

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Added the `--store-to` option to the `%%graph_notebook_config` magic.
> Add store-to option to %%graph_notebook_config

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Disabled line wrapping for result rows
- Reverted font of results to type `monospace` and size `12px`
- Fixed a bug where results table would display ambiguous `Loading...` message for empty results sets
- Fixed a JupyterLab-specific bug where the results table would render with a much greater width than the actual page size 
> Various results table improvements

- .github/workflows/integration.yml
- .github/workflows/unit.yml
- ChangeLog.md
- README.md
- requirements.txt
- setup.py
Issue #, if available: CVE-2021-32862
- Upgraded minimum required Python version to 3.7.0
- Bumped `nbconvert` dependency to `>=6.3.0`
- Removed `traitlets` version pin
> Deprecate Python 3.6 support

- .github/workflows/integration.yml
- Updated `run-tests` step to use Python 3.7, due to previous deprecation of 3.6 support
- Updated `create-stack` step to install newer required dependencies for package build
> Integration test workflow updates

- ChangeLog.md
- README.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #351
- Added `--all-in-queue` flag to `%cancel_load`. When specified, all bulk load jobs with `LOAD_IN_QUEUE` status will be cancelled.
- Added helpful error messaging for when `%cancel_load` receives insufficient arguments.
> Add --all-in-queue option to %cancel_load

- ChangeLog.md
- src/graph_notebook/visualization/templates/gremlin_explain_profile.html
- src/graph_notebook/visualization/templates/opencypher_explain.html
- src/graph_notebook/visualization/templates/sparql_explain.html
Issue #, if available: #362
- Modified profile/explain HTML templates to prevent ipywidgets from automatically collapsing large results. Applies the workaround found [here](https://github.com/jupyter-widgets/ipywidgets/issues/1791#issuecomment-578407750).
> Disable automatic collapsing of large explain results

- src/graph_notebook/network/sparql/SPARQLNetwork.py
- test/unit/network/sparql/data/010_airroutes_no_literals.json
- test/unit/network/sparql/test_sparql_network.py
Issue #, if available: #294
- Allow use of node property values with SPARQL `--group-by`/`--display-property`/`--tooltip-property` visualization options. 
- Change default node group from value of binding `type` -> value of `*:type` property (if available). Group-by-label will also now use the `*:type` property value as the node class identifier.
The `P.` prefix must be added to the property name to signify that we want to look in the node property map, Ex. 
`rdf:type`-> `P.rdf:type`.
Previously, these options would only search within the subject node binding itself. Specifying a property without the `P.` indicator will continue to limit the property search to the binding.
By submitting this pull request, I confirm that my contribution is made under the terms of …
> Support literal property values for Sparql visualization options

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #368
- Fixed `UnboundLocalError` failure occurring when `%db_reset` is unable to retrieve database status within the allotted time limit
- Added new `--max-status-retries` option to `%db_reset`; allows the user to configure the maximum time limit for checking if the database reset has completed.
> Fix %db_reset timeout handling, make timeout limit configurable

- README.md
Description of changes: Fix `start jupyterlab` command in README
> Fix `start jupyterlab` command

- ChangeLog.md
- src/graph_notebook/network/sparql/SPARQLNetwork.py
- test/unit/network/sparql/data/010_airroutes_no_literals.json
- test/unit/network/sparql/test_sparql_network.py
Issue #, if available: #374
- Fixed an issue where the`%%sparql` graph tab would render blank or with the exception `Error: updateGroupOptions: group values in options don't match.`. Properties with multiple values for a single subject will now be handled correctly when used in node grouping.
> Fix Sparql visualizations failing with VisJS group assignment error

- ChangeLog.md
- src/graph_notebook/notebooks/02-Visualization/Grouping-and-Appearance-Customization-Gremlin.ipynb
Issue #, if available: #157
- Updated the `Grouping-and-Appearance-Customization-Gremlin` sample notebook with an example of how to use the `dynamic` edge smoothing setting.
> Update sample notebooks with parallel, same-direction edges example

- ChangeLog.md
- requirements.txt
- setup.py
- Pinning `notebook` dependency to `<6.5.0` to mitigate [a possible bug on `notebook==6.5.1`](https://github.com/jupyter/notebook/issues/6573) causing all CSS rendering to fail in notebook classic.
> Pin notebook to <6.5.0

- src/graph_notebook/seed/queries/propertygraph/security-graph/__init__.py
- Add init file to `propertygraph/security-graph` seed data folder to allow `%seed` to find the files.
> Initialize security-graph seed data

- ChangeLog.md
- src/graph_notebook/__init__.py
- src/graph_notebook/widgets/package.json
> Bump to 3.6.2

- ChangeLog.md
- src/graph_notebook/seed/queries/rdf/epl/0_epl_data.txt
- Fixed an bug where `%seed` would fail to load SPARQL EPL due to a malformed query in the data file.
> Fix SPARQL EPL seed file

- src/graph_notebook/notebooks/01-Getting-Started/02-Using-Gremlin-to-Access-the-Graph.ipynb
Description of changes: Fix edge label / edge type between person (josh) and software (lop) from 'knows' to 'created'.
> Update 02-Using-Gremlin-to-Access-the-Graph.ipynb to fix edge label

- ChangeLog.md
- src/graph_notebook/widgets/package.json
Issue #, if available: #392
- Upgraded `graph_notebook_widgets` dev dependency `typescript` from `3.8.3` to `4.1.6`. This brings us back in line the TypeScript version used by `@jupyterlab/buildutils`: https://github.com/jupyterlab/jupyterlab/blob/3.6.x/buildutils/package.json#L59
> Bump typescript to 4.1.x in graph_notebook_widgets

- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/neptune/client.py
- test/integration/IntegrationTest.py
- test/unit/configuration/test_configuration_from_main.py
- Changed `%%graph_notebook_config` default behavior to enforce Neptune-specific configuration options only when the host is a Neptune endpoint (i.e. `*.neptune.amazonaws.com` or `*.neptune.*.amazonaws.com.cn`), rather than any AWS endpoint (`*.amazonaws.com`). This allows non-Neptune configuration options to be used for AWS endpoints hosting separate graph databases.
> Enforce Neptune-specific config only for Neptune endpoints

- README.md
- Fixed Neptune ML descriptions in README to list NeptuneML docs instead of the splash page.
> Update NeptuneML links in README

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Fixed status widgets for `%db_reset` not appearing in JupyterLab
- Fixed progress wheel not displaying for first reset status check interval
> %db_reset status output bugfixes

- ChangeLog.md
- requirements.txt
- setup.py
Issue #, if available: #397
- Pinned `ipywidgets` dependency to `<=7.x` to resolve issues caused by incompatibility with the latest major version.
> Pin ipywidgets to <=7.7.1

- additional-databases/sagemaker/install-graph-notebook-lc-cn.sh
- additional-databases/sagemaker/install-graph-notebook-lc.sh
- Added pre-installation of `notebook==6.4.12`; fixes CSS rendering issue when launching notebook classic on Sagemaker instances
- Added pre-installation of `ipywidgets<=7.7.1` to resolve conflicts between base `graph-notebook` package and `ipywidgets>=8.x`.
> Update sample SageMaker lifecycles to latest versions

- ChangeLog.md
- additional-databases/sagemaker/install-graph-notebook-lc-cn.sh
- additional-databases/sagemaker/install-graph-notebook-lc.sh
- requirements.txt
- setup.py
- Pinning `nbclient<=0.7.0` to avoid breaking changes in later versions. `nbclient>=0.7.1` replaces `nest_asyncio` usage with `run_sync` from `jupyter_core>=5.x`, which is incompatible with Python 3.7.
> Pin nbclient<=0.7.0

- ChangeLog.md
- src/graph_notebook/notebooks/05-Data-Science/02-Logistics-Analysis-using-a-Transportation-Network.ipynb
Issue #, if available: #403
- Resolved error in igraph object creation command for [02-Logistics-Analysis-using-a-Transportation-Network](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/notebooks/05-Data-Science/02-Logistics-Analysis-using-a-Transportation-Network.ipynb). Thanks to @osman-santos for providing the fix.
> Fixed igraph error in 02-Logistics-Analysis-using-a-Transportation-Network

- ChangeLog.md
- requirements.txt
- setup.py
- Fixes an issue with widgets failing to render in JupyterLab on the 3.7.0 pre-release build. This commit ensures that our `ipywidgets` 7.x dependency will not accidentally install an incompatible higher version of `jupyterlab_widgets`. 
- Related: https://github.com/jupyterlab/jupyterlab/issues/12977
> Pin jupyterlab_widgets<3, bump to ipywidgets==7.7.2

- ChangeLog.md
- src/graph_notebook/notebooks/04-Machine-Learning/Sample-Applications/01-People-Analytics/People-Analytics-using-Neptune-ML.ipynb
- Fixed a bug in the [01-People-Analytics/People-Analytics-using-Neptune-ML](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/notebooks/04-Machine-Learning/Sample-Applications/01-People-Analytics/People-Analytics-using-Neptune-ML.ipynb) sample notebook, where the endpoint creation step would fail due to invalid arguments.
> Use correct endpoint arguments in People Analytics ML notebook

- ChangeLog.md
- README.md
- requirements.txt
- setup.py
Issue #, if available: #414
- Pinning `numpy<1.24.0`. This ceiling restriction resolves a conflict with our dependency `networkx==2.4.0` , which requires the use of `np.int` removed in the latest version of numpy.
> Pin numpy<1.24.0

- requirements.txt
Issue #, if available: CVE-2022-40897
- Upgraded `setuptools` dependency for a vulnerability fix. This upgrade is inconsequential, as we have already been building our most recent PyPi releases on `setuptools==65.x`.
> Bump setuptools from 40.6.2 to >=65.5.1

- ChangeLog.md
- src/graph_notebook/magics/metadata.py
Issue #, if available: #422
- Rounded down metadata metrics `Query execution time` and `Request execution time` to two decimal places. This will improve readability, and match the precision of most metrics returned from Neptune Profile and Explain APIs.
> Truncate metadata request/query time metrics

- ChangeLog.md
- src/graph_notebook/widgets/src/force_widget.ts
Issue #, if available: #421
- Modified graph widget to use [prefixed Fullscreen API attributes](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API/Guide#prefixing) to fix browser-specific issues. Derived from the solution provided by @jklap in the referenced issue. These changes have been verified on Safari 16.2, Firefox 102.5.0esr, Chrome 109.x, and Edge 109.x.
> Fix browser-specific issues with fullscreen graph widget

- ChangeLog.md
- README.md
- requirements.txt
- setup.py
Issue #, if available: #428
- Pinning ceiling of `itables` dependency to `<1.4.3`. This fixes an error occurring when attempting to render the results table widget via query magics.
> Pin itables<1.4.3

- ChangeLog.md
- src/graph_notebook/neptune/bolt_auth_token.py
- src/graph_notebook/neptune/client.py
- Fixed a bug where `%%oc bolt` could fail with an authentication error when making queries to an IAM-enabled Neptune cluster with engine version 1.2.0.0 or later. 
> Use updated authentication method for IAM Bolt queries

- ChangeLog.md
- test/unit/notebooks/test_validate_notebooks.py
> #417 test and changelog

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Added a new `--profile-misc-args` option for `%%gremlin profile` to allow passing custom data in the request. This argument accepts a map-format string via variable injection.
Example usage:
> Add --profile-misc-args option to %%gremlin

- src/graph_notebook/widgets/package.json
- Fixed a CI builds error related to a conflict between Webpack 4.x and newer versions of NodeJS 18.x. See: https://github.com/webpack/webpack/issues/14532
> Fix Webpack failure in CI builds

- .github/workflows/unit.yml
- src/graph_notebook/widgets/package.json
- Reverting #447 in favor of pinning to a stable Node version in the unit test workflow; the OpenSSL legacy support option breaks our ECR deployment workflow, which runs on Node 12.x.
> Pin NodeJS 14.x in unit.yml

- .github/workflows/docker_publish.yml
- Added an option for manually triggering `docker_publish.yml`, to make it easier to deploy both latest and versioned release images to ECR.
> Add manual trigger for ECR publish workflow

- ChangeLog.md
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
- Modified `%%gremlin --group-by` behavior for map type vertices. If a vertex does not contain the property specified by `--group-by`, it will be assigned to group `DEFAULT_GROUP` instead of having no group assignment.
> Ensure default assignments for all Gremlin nodes when using grouping

- ChangeLog.md
- src/graph_notebook/configuration/get_config.py
Issue #, if available: #452
- Print a warning and list of ignored parameters when attempting to set `%%graph_notebook_config` with incompatible fields for a given non-Neptune host.
> Add error messaging for incompatible host-specific config params

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Fixed an issue where `--store-to` had no effect for `%statistics` and `%summary`, and moved a few other magics over to the newer assignment function.
> Fix --store-to option for several magics

- ChangeLog.md
- Dockerfile
- Fixed Dockerfile builds breaking due to `yum install python3` installing Python 3.7 by default, we now ensure that a compatible version of Python 3.8 is installed via `amazon-linux-extras` package.
- Upgraded Node to 14.x in Dockerfile.
- Pin `twine` to resolve a conflict with our required `urllib` version.
> Enforce Python 3.8 usage in Dockerfile

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/network/gremlin/GremlinNetwork.py
- test/unit/network/gremlin/test_gremlin_network.py
- Fixed an issue where the graph widget would fail to render for Gremlin query results containing vertex or edge IDs values of UUID type, due to a JSON serialization error.
- Catch exceptions from `gremlin_network` and Force widget generation separately, to make visualization debugging easier.
- Related question on StackOverflow: https://stackoverflow.com/questions/75986863/aws-jupyter-notebook-dont-show-graph-tab-after-changed-gremlin-settings
> Fix Gremlin visualizations failing to render with UUID type IDs

- .github/workflows/unit.yml
- ChangeLog.md
- README.md
- requirements.txt
- setup.py
- Loosened up some dependency minimum version requirements to reinstate support for Python 3.7. This continues support for legacy Neptune Notebooks on `notebook-al1-v1` platform that cannot be upgraded from Python 3.7.
> Reinstate Python 3.7 support

- .github/workflows/integration.yml
- .github/workflows/unit.yml
- ChangeLog.md
- Dockerfile
- README.md
- [JupyterLab 4.0.0](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.0) was released yesterday, and is breaking some of our recent CI builds for Python 3.8/3.10 ([Example](https://github.com/aws/graph-notebook/actions/runs/4988030679/jobs/8930366762)). Pinning JupyterLab 3.x until we can officially add support for JupyterLab 4.
> Pin JupyterLab<4.x

- .github/workflows/integration.yml
- .github/workflows/unit.yml
- ChangeLog.md
- Dockerfile
- README.md
Can't think of a reason for "amount" to be non-numeric. Would be nice to be able to do `sum()` and or different equality functions on that property value as a number. 
> Converted "amount" datatype from String to numeric for "Transaction"  vertices

- requirements.txt
- setup.py
Issue #, if available: CVE-2023-32681
- Upgraded `requests` dependency maximum version for a security fix.
> Bump requests ceiling to 2.31.0

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- test/integration/iam/notebook/test_open_cypher_graph_notebook.py
Issue #, if available: #454
- Added a new `-qp`/`--query-parameters` option to the `%%oc` magic. Users can now apply arguments to the query following the format specified in the Neptune [docs](https://docs.aws.amazon.com/neptune/latest/userguide/opencypher-parameterized-queries.html).
Example usage:
> Support parameterized queries for openCypher

- ChangeLog.md
- src/graph_notebook/neptune/client.py
- test/unit/configuration/test_configuration.py
- test/unit/configuration/test_configuration_from_main.py
- Prevent `InsecureRequestWarning` from being displayed during magics execution, if `ssl_verify=False` is set in the notebook configuration.
- Added extra unit tests for the `ssl_verify` config option.
> Suppress InsecureRequestWarning if SSL verification is disabled

- src/graph_notebook/notebooks/01-Getting-Started/01-About-the-Neptune-Notebook.ipynb
Resolved "Variable `n` already declared (line 3, column 9 (offset: 46))" issue.
> Resolved openCypher query issue

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- Added the `--explain-type` option to `%%gremlin`
- Changed `--explain-type` option in `%%sparql` and `%%oc` to accept arbitrary string input.
> Add --explain-type option to %%gremlin

- .github/workflows/integration.yml
Resolve #505 
Update `.github/workflows/integration.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
I found the workflow file that use `set-output` command through the following command:
```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```
**AS-IS**
```yaml
run: echo "::set-output name=stack-name::$(echo graph-notebook-$RANDOM)"
```
**TO-BE**
```yaml
run: echo "stack-name=$(echo graph-notebook-$RANDOM)" >> $GITHUB_OUTPUT
```
By submitting this pull …
> Replace deprecated command with environment file

- README.md
Issue #399 
I have enhanced the documentation for the graph_notebook_config table to include all possible properties and clarify when the proxy_host and proxy_port are exclusively utilized for Amazon Neptune, plus fixed all markdown warnings in README.
> updates to graph_notebook_config for Amazon Neptune Proxy Connection

- ChangeLog.md
- additional-databases/sagemaker/sagemaker-notebook-lifecycle/install-graph-notebook-lc-cn.sh
- additional-databases/sagemaker/sagemaker-notebook-lifecycle/install-graph-notebook-lc.sh
- requirements.txt
- setup.py
Issue #, if available: #516
- Upgrade to `notebook` pin ceiling to `<7.0.0` to mitigate: https://github.com/jupyter/notebook/issues/6721.
- Cleaned up legacy version pins in SageMaker Lifecycle scripts.
> Fix notebook kernel crashing with ZMQ errors on magic execution

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Fixed an issue with `%seed` where descriptions of some of the drop-down widgets were partially obscured.
> Realign %seed widgets to fix truncated descriptions

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- src/graph_notebook/network/gremlin/GremlinNetwork.py
Issue #, if available: #399
- Fixed an issue with `%%gremlin` not utilizing the `proxy_host` and `proxy port` field values set in the notebook connection configuration. 
- When a proxy is specified, Gremlin requests to Neptune will now be executed against the [HTTPS REST endpoint](https://docs.aws.amazon.com/neptune/latest/userguide/access-graph-gremlin-rest.html), and require engine version >=1.2.1.0.R5. 
- Proxied Gremlin queries against all other databases will continue to use the gremlin-python client.
- Added support for visualizing Gremlin results returned in GraphSONv1 format.
> Add support for Gremlin proxy host and Neptune HTTP query visualization

- src/graph_notebook/notebooks/06-Language-Tutorials/03-Gremlin/02-Loops-Repeats.ipynb
- Fixed an issue in the Gremlin `02-Loops-Repeats` tutorial notebook, where some variable hops queries could fail on Neptune with `MemoryLimitExceeded` exception.
> Query fixes for Gremlin tutorial notebooks

- src/graph_notebook/decorators/decorators.py
- Fixed an issue where some notebook magics marked by the `@neptune_db_only` decorator would not function correctly when using `neptune-db` service.
> Fix `@neptune_db_only` magics decorator

- ChangeLog.md
- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/configuration/get_config.py
- test/unit/configuration/test_configuration.py
- test/unit/configuration/test_configuration_from_main.py
- Removed the restriction on setting custom values for the Gremlin `message_serializer` field in `%%graph_notebook_config` when a Neptune endpoint is specified.
> Allow custom Gremlin serializers for Neptune

- .github/workflows/unit.yml
- ChangeLog.md
- README.md
- setup.py
- Deprecating support for Python 3.7 due to discontinuation of security support. Additionally, this change ensures compatibility with the latest versions of Boto library, which have also [removed 3.7 support](https://github.com/boto/boto3/blob/59b53f94d5992a1d252b2ba15d3c8283f94f047c/.changes/1.34.0.json#L4) and [added the `neptune-graph` SDK](https://github.com/boto/boto3/blob/59b53f94d5992a1d252b2ba15d3c8283f94f047c/.changes/1.34.1.json#L43). 
> Deprecate Python 3.7 support

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Added support for using abbreviated memory units with %%gremlin's `-mcl`/`--max-content-length` parameter. Provided short forms (ex. `50MB`) will be automatically converted for the final Gremlin request.
> Support unit abbreviations for --max-content-length

- ChangeLog.md
- requirements.txt
- setup.py
Issue #, if available: CVE-2024-22195
- Bump `Jinja2` dependency ceiling for a security fix.
> Bump Jinja2 to 3.1.3

- ChangeLog.md
- src/graph_notebook/notebooks/02-Neptune-Analytics/02-Graph-Algorithms/06-Vector-Similarity-Algorithms.ipynb
- src/graph_notebook/notebooks/02-Neptune-Analytics/03-Sample-Use-Cases/02-Investment-Analysis/01-EDGAR-Competitor-Analysis-using-Knowledge-Graph-Graph-Algorithms-and-Vector-Search.ipynb
- test/unit/notebooks/test_validate_notebooks.py
Issue #, if available: #564
- Updated a few `create-graph` commands for compatibility with latest CLI.
> Update Neptune Analytics CLI commands in samples

- ChangeLog.md
- src/graph_notebook/decorators/decorators.py
- Added a new decorator function for restricting usage of magics only supported for Neptune Analytics.
> Add @neptune_graph_only decorator

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
Issue #, if available: #568
- Added a new `%graph_pg_info` line magic for use with Neptune Analytics. This magic serves as a convenient wrapper for running the `graph.pg_info` algorithm via `%%oc` query.
Example usage:
- Running `%graph_pg_info` returns all available graph metrics and their counts.
- Using the `-m [metric_name]` option will return the count of the specified metric.
> Add %graph_pg_info line magic

- ChangeLog.md
- additional-databases/sagemaker/neptune-notebook-cloudformation/README.md
- additional-databases/sagemaker/neptune-notebook-cloudformation/neptune-workbench-stack.yaml
- Updates to the sample NeptuneDB Notebook CloudFormation template for ease of use:
- Automated creation of IAM role and tags.
- Explicitly set `neptune-graph` service parameter.
- Made IAM `auth_mode` parameter configurable.
> Improve CloudFormation template for Neptune DB Notebook

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Escaped parameterized query symbols in certain `%%oc explain` results to prevent unintended formatting.
- Fixed content of store-to for `%%oc explain`.
> Fixed formatting in openCypher explain widget

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Replaced `%load` `--fail-on-failure` with a new `--no-fail-on-error` parameter. This will also change the default passed value of `failOnError` to match the Neptune Bulk Loader [documentation](https://docs.aws.amazon.com/neptune/latest/userguide/load-api-reference-load.html#load-api-reference-load-parameters).
> Change %load failOnError default behavior

- src/graph_notebook/network/opencypher/OCNetwork.py
- test/unit/network/opencypher/test_opencypher_network.py
Issue #, if available: #537
- Disabled metadata property inference in the openCypher visualizer. This will allow for usage of custom `id`/`labels`/`type` node properties in group, label, and tool-tip settings.
> Remove property inference from openCypher visualizer

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #579
- Added a new `--store-format` option to the `%%gremlin`/`%%oc`/`%%sparql` magic commands. This option allows users to choose between JSON dictionary (default) or Pandas DataFrame format when saving query mode results with `--store-to`.
- Restored DataTables formatting to the `%%sparql` results widget.
Example usage:
```
%%oc --store-to a_variable --store-format pandas
...
```
> Add --store-format option to query magics

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #583
- Fixed an bug where `%%oc --query-param` values of type `None` would cause Neptune queries to fail.
> Fix NoneType serialization for OC query params

- ChangeLog.md
- README.md
- src/graph_notebook/__init__.py
- src/graph_notebook/widgets/package.json
- Incrementing package version to 4.2.0.
> Release 4.2.0

- requirements.txt
- setup.py
Issue #, if available: CVE-2024-34064
- Bump `Jinja2` ceiling to 3.1.4 for a security fix.
> Bump Jinja2 to 3.1.4

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #591
- Fixed a `%%gremlin` bug where the results DataFrame would fail to create when processing both list and vertex/string type elements.
> Improve handling of mixed type Gremlin results

- src/graph_notebook/magics/graph_magic.py
- Fixed the formatting of several `%%oc`/`%%gremlin`/`%%sparql` `--help` entries for arguments accepting a pre-defined list of valid inputs.
> Fix argument help messages for query magics

- ChangeLog.md
- src/graph_notebook/notebooks/03-Neptune-ML/03-Sample-Applications/01-People-Analytics/People-Analytics-using-Neptune-ML.ipynb
Issue #, if available: 594
- Fixed the training job ID parameters being passed to the second `%neptune_ml endpoint create` command in the `People-Analytics-using-Neptune-ML` sample notebook.
> Fix endpoint creation in People-Analytics-using-Neptune-ML sample

- ChangeLog.md
- requirements.txt
- setup.py
- src/graph_notebook/network/sparql/SPARQLNetwork.py
- src/graph_notebook/notebooks/03-Neptune-ML/02-SPARQL/neptune_ml_sparql_utils.py
Issue #, if available: #439
- Updating the `rdflib` and `SPARQLWrapper` dependencies to the latest versions supported by Python 3.8.
- Fixed deprecated usage of Pandas `DataFrameGroupBy.mean` in NeptuneML SPARQL utils
> Update to RDFLib 7.0.0 and SPARQLWrapper 2.0.0

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #598
- Display warnings when attempting to pass `--plan-cache` or `--query-timeout` parameters to `%%oc` while connected to a Neptune DB endpoint.
- Added better `--help` documentation for the `%%oc` Neptune Analytics parameters. 
> Add warnings for usage of `%%oc` with incompatible Neptune Analytics parameters

- src/graph_notebook/magics/graph_magic.py
- Fixed a issue with some `%%sparql` queries where the results table copy/download buttons would only export the first column of selected results.
> Fix datatables export options for %%sparql

- ChangeLog.md
- src/graph_notebook/configuration/generate_config.py
- test/unit/configuration/test_configuration.py
Issue #, if available: #604
- Modified the dummy configuration generated for `%graph_notebook_config` to also display fields restricted to Neptune endpoints.
> Include Neptune parameters in default %graph_notebook_config

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- Added a new `%get_graph` line magic for Neptune Analytics. This magic calls the [GetGraph](https://docs.aws.amazon.com/neptune-analytics/latest/apiref/API_GetGraph.html) API to retrieve information about the graph host specified in `%graph_notebook_config`.
- Enabled `%status` for Neptune Analytics as a redirect for `%get_graph`.
> Add `%get_graph` line magic, enable `%status` for Neptune Analytics

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- Added a new `-cp`/`--connection-protocol` option to `%%gremlin`, allowing users to switch freely between `http` and `websockets` for Neptune connections. WebSockets will remain the default protocol for `query` mode, while the option will not affect `profile` or `explain` mode, which must use HTTP.
> Add `--connection-protocol` option to %%gremlin

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #619
- Restored left alignment of numeric value columns in results table, which was lost in v4.3.1 due to breaking changes introduced with DataTables 2.x. 
> Fix alignment of numeric values in results table

- ChangeLog.md
- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/configuration/get_config.py
- src/graph_notebook/magics/graph_magic.py
- test/unit/configuration/test_configuration.py
- Added a new `connection_protocol` field to the Gremlin section of `%%graph_notebook_config`, to support switching between WebSockets and HTTP connections. This setting will apply globally to all `%%gremlin` queries to Neptune endpoints, although it can still be overridden by the `%%gremlin --connection-protocol` argument.
> Add global Gremlin `connection_protocol` field to notebook configuration

- ChangeLog.md
- src/graph_notebook/configuration/get_config.py
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/magics/metadata.py
- src/graph_notebook/neptune/client.py
- Various compatibility changes for submitting queries to Neptune over HTTP.
- Set default value of `%%gremlin --explain-type` to `dynamic`.
- Added new `--profile-debug` toggle parameter to `%%gremlin`.
> Enhancements for Gremlin HTTP

- ChangeLog.md
- src/graph_notebook/configuration/generate_config.py
- test/unit/configuration/test_configuration_from_main.py
- Improved arg-based calls directly to `generate_config` module by setting Gremlin `connection_protocol` defaults based on the service argument.
> Improve Gremlin protocol auto-sets when generating config via arguments

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #629
- Fixed an issue where `%%gremlin --help` would fail due to an unescaped special character in the `--connection-protocol` docstring.
> Fix broken `%%gremlin --help` command

- ChangeLog.md
- src/graph_notebook/notebooks/01-Neptune-Database/01-Getting-Started/01-About-the-Neptune-Notebook.ipynb
- Fixed an openCypher query execution bug in [`01-About-the-Neptune-Notebook`](https://github.com/aws/graph-notebook/blob/main/src/graph_notebook/notebooks/01-Getting-Started/01-About-the-Neptune-Notebook.ipynb) caused by an accidental reversion of https://github.com/aws/graph-notebook/pull/501 in the changes introduced with https://github.com/aws/graph-notebook/pull/541.
> Fix openCypher query regression in `01-About-the-Neptune-Notebook` sample 

- ChangeLog.md
- src/graph_notebook/configuration/get_config.py
- test/unit/configuration/test_configuration.py
Issue #, if available: #632
- Fixed an issue where setting `%%graph_notebook_config` for non-Neptune hosts would fail unless the optional `gremlin` sub-section was included in the JSON.
- Added unit tests to validate required/optional/allowed fields for `get_config`.
> Fix `%%graph_notebook_config` error when excluding optional Gremlin section

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Added a new `--connected-table` option to `%%gremlin`/`%%sparql`/`%%opencypher`/`%%load_ids`. When specified, this option will enable [iTables connected mode](https://mwouts.github.io/itables/quick_start.html#offline-mode-versus-connected-mode).
- Changed default behavior of results table widget to enforce offline mode.
> Add `--connected-table` option to query magics

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #636
- Fixed an issue with `%load` where the value of the `--mode` argument would not be passed with bulk loader requests to NeptuneDB hosts. 
> Fix `--mode` argument in `%load`

- src/graph_notebook/widgets/package.json
- Added a `"@types/lodash": "4.17.2"` pin to prevent TypeScript compilation errors when building the graph_notebook_widgets package.
> Pin `@types/lodash` to 4.17.2

- ChangeLog.md
- src/graph_notebook/visualization/template_retriever.py
- src/graph_notebook/visualization/visualizer.py
Issue #, if available: CVE-2019-8341
- Switching Jinja2 `Template()` usages to `SandboxedEnvironment.from_string()` to mitigate a vulnerability.
> Generate Jinja2 templates in sandboxed environment

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Fixed `%%gremlin` magic command to return error messages along with query results when using `--store-to`.
> Store exception messages when using `%%gremlin --store-to`

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Added the `--silent` option to the `%%graph_notebook_config` line and cell magics.
> Add silent option to `%%graph_notebook_config`

- ChangeLog.md
- src/graph_notebook/decorators/decorators.py
- Added more helpful user guidance for select magics restricted by the `%neptune_db_only` or `%neptune_graph_only` decorators. Users will be directed to use an alternative magic specific to the configured `neptune_service`, where available.
> Add redirect messaging for service-restricted Neptune magics

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- Added a new `%reset` magic compatible with both Neptune Database and Neptune Analytics. `%reset` inherits all of the original arguments of `%db_reset` and `%graph_reset`/`%reset_graph`, which now wrap the `%reset` and call it with the corresponding service.
- Renamed the `%graph_reset` `-ns`/`--no-skip-snapshot` argument to `-s`/`--snapshot`.
Example UI for Neptune Analytics:
> Add unified `%reset` magic

- ChangeLog.md
- requirements.txt
Issue #, if available: CVE-2024-6345
- Bumped `setuptools` requirement to >=70.0.0 to address a vulnerability.
> Bump setuptools to 70.x

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #651
- Diverging `%reset` outputs on retry timeout to be relevant/helpful for the current Neptune service.
> Improve `%reset` status user messaging on retry timeout

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
Issue #, if available: #651
- Added a new `%create_graph_snapshot` for Neptune Analytics. This magic interfaces with the [CreateGraphSnapshot API](https://docs.aws.amazon.com/neptune-analytics/latest/apiref/API_CreateGraphSnapshot.html), the supported parameters of which can be passed via optional line arguments:
- `-s`/`--snapshot-name`: Sets the `snapShot` string parameter. If not supplied, the notebook will automatically create and use a name in the format `snapshot-[graph_id]-[timestamp]`.
- `-t`/`--tags`: Sets the `tags` parameter. Accepts a map in string format, ex. `{"tag1":"foo","tag2":"bar"}`.
Example usage:
> Add `%create_graph_snapshot` line magic

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
Issue #, if available: #651
- Changed the Neptune Analytics `--snapshot` option for `%reset` to call and poll the CreateGraphSnapshot API, instead of  passing `skipSnapshot=False` with the GraphReset API call. This ensures that `--snapshot` will work even on graphs where `skipSnapshot` is unsupported.
> Use CreateGraphSnapshot API for `%reset --snapshot` 

- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- Added new `%neptune_client_endpoint` line magic. Allows users to set a custom [endpoint_url](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.client) to use when initializing the `neptune-graph` SDK client.
- Modified `%%neptune_config_allowlist` to regenerate notebook client upon allowlist modification
**Example usage:**
To set the custom endpoint_url, run:
```
%neptune_client_endpoint https://your.endpoint.url.here
```
To reset the endpoint_url to the default constructed by Boto3, run:
To check the current endpoint_url state, specify no arguments:
> Add `%neptune_client_endpoint` line magic

- ChangeLog.md
- setupbase.py
This PR addresses a bug that occurs when building the **graph-notebook** with Python3.11. The [Porting to Python 3.11 summary](https://docs.python.org/3/whatsnew/3.11.html#porting-to-python-3-11) calls out a change to global inline flags so that they can **only** be used at the start of a regular expression.
The existing code for converting globs -> regexes  appends the `(?ms)` modifier at the end of the pattern. This PR removes the [multiline](https://docs.python.org/3/library/re.html#re.MULTILINE) and [dotall](https://docs.python.org/3/library/re.html#re.DOTALL) modifiers from the regex string template. Instead, it uses the **multiline** and **dotall** flags in the compile statement.
This allows the `graph-notebook` library to, at a minimum, build with Python3.11
By submitting this pull …
> fix: updates to allow building the library Python 3.11

- .github/workflows/unit.yml
- ChangeLog.md
- requirements.txt
- setup.py
- Added Python 3.11 to the GitHub unit tests workflow
- Fixed an issue where widgets installation would fail due on 3.11 due to a GremlinPython dependency error
> Enable unit tests and fix widgets installation on Python 3.11

- ChangeLog.md
- additional-databases/sagemaker/sagemaker-notebook-lifecycle/install-graph-notebook-lc-cn.sh
- additional-databases/sagemaker/sagemaker-notebook-lifecycle/install-graph-notebook-lc.sh
- Renamed custom kernel to `Neptune_Python3` for easier differentiation from native SageMaker kernels
- Removed unused notebook version parameter parsing
> Update sample SageMaker lifecycles to latest

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Removed the `--periodic-commit` option from `%load`, as it currently has no effect on batch load requests.
> Remove unused options from `%load`

- ChangeLog.md
- additional-databases/sagemaker/neptune-notebook-cloudformation/neptune-workbench-stack.yaml
- Removed EncryptionKey parameter requirement in the Neptune SageMaker noteobook CloudFormation template.
> Make EncryptionKey optional in Neptune CloudFormation template

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #673
- Hardcode required `'blankNodeHandling': 'convertToIri'` parameter when executing `%load --format ntriples` against Neptune Analytics.
> Pass `blankNodeHandling` option to batch `%load`

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #678
- Modified query magics to convert all results to Pandas dtypes compatible with null values, in order to prevent unintended type coercion during results table creation.
> Convert numerics to null-supported Pandas types

- ChangeLog.md
- requirements.txt
- setup.py
- Bumped `neo4j` dependency floor from 4.4.x to 5.x.
> Upgrade Neo4j Python Driver to 5.x

- ChangeLog.md
- src/graph_notebook/ipython_profile/configure_ipython_profile.py
Apply IPython's own logic to retrieve the location of the IPython configuration directory as detailed in the [docs](https://ipython.readthedocs.io/en/stable/development/config.html#configuration-file-location). This allows reuse of custom config dirs like ~/.config/ipython or any path specified via IPYTHONDIR environment variable.
> Fix IPython config dir retrieval logic

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #690
- Fixed an `%db_reset` bug with the `--generate-token` and `--token` modes, where the output returned from the wrapped `%reset` magic would not be displayed to the user.
> Fix missing `%db_reset` output for token modes

- ChangeLog.md
- setup.py
Specify test dependency in `extras_require` instead of `tests_require`.  
Reason: The latter is deprecated. See https://github.com/pypa/setuptools/blob/bb0506352435a13f6fd70fa3b9eae6fd0f6e1ea8/docs/references/keywords.rst?plain=1#L452-L467
P.S.: This change (together with setting environment variable `NODE_OPTIONS="--openssl-legacy-provider"` for a totally different reason), allows to specify graph-notebook as a git-based dependency in a pyproject.toml and to install it using `poetry`:  
```
[tool.poetry.group.dev.dependencies]
graph-notebook = { git = "https://github.com/bauer-at-work/graph-notebook", branch = "main" }
```
> use extras_require to specify tests

- ChangeLog.md
- requirements.txt
- setup.py
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- Updated certain Gremlin HTTP request formatting, and handling of error response with incomplete JSON.
> Update Gremlin HTTP requests and error handling

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
Issue #, if available: #693
- Switched the default value of the `%%gremlin profile --profile-serializer` option from `GRAPHSON_V3_UNTYPED` to `GRAPHSON_V3` (typed). This fixed a backwards compatibility issue with Neptune Database instances on major engine version 1.2 or older.
> Fix `%%gremlin profile` serializer issue on Neptune DB <=1.2.x

- ChangeLog.md
- requirements.txt
- setup.py
- Moved `nest_asyncio` to 1.6.0 for improved compatibility with third party libraries.
> Bump nest_asyncio to 1.6.0

- ChangeLog.md
- src/graph_notebook/configuration/generate_config.py
- src/graph_notebook/configuration/get_config.py
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- test/unit/configuration/test_configuration.py
- test/unit/configuration/test_configuration_from_main.py
- Reworked Gremlin config generation to set allowed inputs and defaults for `connection_protocol` and `message_serializer` based on service type
- Fixed `message_serializer` not enforcing serializer input compatible with the GremlinPython driver when connecting to non-Neptune endpoints
- Temporarily restricted `message_serializer` to GraphSON-untyped serializers on HTTP connections
> Enforce Gremlin protocol and serializer based on database type

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- Enabled the `--query-timeout` parameter when using `%%oc explain` mode with Neptune Analytics.
> Enable query timeout for Neptune Analytics explains

- ChangeLog.md
- src/graph_notebook/neptune/client.py
- Changed `%%oc` to use the port-less `/queries` endpoint for Neptune Analytics.
> Use /queries endpoint for openCypher

- src/graph_notebook/magics/graph_magic.py
- Reverted an unintended `%seed` change in v4.6.1.
> Disable Gremlin datasets for `%seed` on Neptune Analytics

- ChangeLog.md
- src/graph_notebook/magics/graph_magic.py
- src/graph_notebook/neptune/client.py
- Added a `--use-port` option to `%%gremlin` and `%%oc`. Specifying this option ensures that the configured port is passed for Neptune HTTP requests.
> Add `--use-port` option to %%gremlin and %%oc

- ChangeLog.md
- additional-databases/fuseki/README.md
Issue #, if available: #702
- Fixed an issue in the Fuseki documentation where the example configuration contained a read-only path.
> Fix SPARQL path in Fuseki docs

- ChangeLog.md
- requirements.txt
- setup.py
Issue #, if available: #714
- Pinned `jupyterlab-widgets<=1.1.10` to mitigate visualization widget crashing on later versions due to JupyterLab 4 support requirement.
> Mitigated visualization widget crash on newer `jupyterlab-widgets` versions

- ChangeLog.md
- README.md
- src/graph_notebook/__init__.py
- src/graph_notebook/widgets/package.json
- Increment package version to 4.6.2
> Release 4.6.2

- ChangeLog.md
Updating changelog after JupyterLab 4x upgrade.
> Update ChangeLog for v5.0.0

- pyproject.toml
- requirements.txt
Issue #, if available: https://github.com/aws/graph-notebook/issues/734
Description of changes: locked numba dependency to 0.60.0 to avoid numpy conflict
> locked numba dependency to 0.60.0 to avoid numpy conflict

- pyproject.toml
- requirements.txt
- src/graph_notebook/start_notebook.py
- src/graph_notebook/widgets/webpack.config.js
Issue #, if available: [Issue #738](https://github.com/aws/graph-notebook/issues/738)
This PR addresses issues with extension loading in Jupyter Notebook Classic (NBClassic) environments. The changes modify the webpack configuration to ensure proper module definition and loading.
1. Modified the first nbextension output:
- Changed `libraryTarget` from "amd" to "var"
- This ensures the extension is properly exposed as a global variable, which is necessary for NBClassic's initial extension loading process
2. Adjusted the second nbextension output:
- Removed the `library` name for the AMD module (set to `undefined`)
- This allows for proper AMD module definition without potential namespace conflicts
These changes align our extension with the expected module loading …
> fixed library target for nbclassic nbextension for graph_notebook_widget

- src/graph_notebook/options/options.py
- src/graph_notebook/widgets/src/force_widget.ts
- test/unit/options/test_options.py
**Issue**
Node selection highlighting was not working in the force-widget graph visualization component.
The issue was caused by incompatible changes in the vis-network package dependency versions, which affected the graph-notebook selection functionality.
**Changes Made**
- Updated the node selection implementation to align with the new vis-network package requirements
- Fixed the highlighting behavior for selected nodes in the graph visualization
> Fix selected node highlights in force widget

- ChangeLog.md
- README.md
- pyproject.toml
- src/graph_notebook/__init__.py
- src/graph_notebook/widgets/package.json
N/A
Bumping version to 5.0.1 to create a new release.
> Bump to 5.0.1

- Dockerfile
N/A
This PR fixes the dockerfile to work as per the toml build system that was introduced with Jupyterlab 4x changes. 
> updated dockerfile to run with jupyterlab 4 build system

- src/graph_notebook/magics/graph_magic.py
Issue #732, if available:
+ Add new boolean field for edgeOnlyLoad parameter
+ Support edgeOnlyLoad for neptune-db only
> Support edgeOnlyLoad param for load magic
